baseURL = "https://www.meexia.com/"
languageCode = "en-gb"
title = "Dioni Zhong"
theme = "cactus"
copyright = "Dioni Zhong" # cactus theme will use site title if copyright is not set

# summaryLength = 2

# Main menu which appears below site header.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "Writings"
url = "/writings"
weight = 3

[[menu.main]]
name = "Courses"
url = "/courses"
weight = 4

[[menu.main]]
name = "VFX"
url = "/vfx"
weight = 5

[[menu.main]]
name = "Games"
url = "/games"
weight = 6

[[menu.main]]
name = "Previous Lives"
url = "/about"
weight = 7

[markup]
  [markup.tableOfContents]
    endLevel = 4
    ordered = false
    startLevel = 2

[params]

  colortheme = "white" # dark, light, white, or classic
  rss = true # generate rss feed. default value is false
  googleAnalyticsAsync = true # use asynchronous tracking. Synchronous tracking by default
  css = ["css/custom.css"]

  # Home page settings
  description = "I'm a Senior Software Engineer in EdTech. Prior to that I worked on movies and video games. I'm working towards a (second) degree in English Literature and Creative Writing. Recent obsession: crypto, blockchain and decentralisation."
  mainSection = "posts" # your main section
  showAllPostsOnHomePage = false # default
  postsOnHomePage = 5 # this option will be ignored if showAllPostsOnHomePage is set to true
  tagsOverview = true # show tags overview by default.
  showProjectsList = false # show projects list by default (if projects data file exists).
  projectsUrl = "https://github.com/gohugoio" # title link for projects list

  # https://gohugo.io/functions/format/#hugo-date-and-time-templating-reference
  dateFormat = "2006-01-02" # default

  # Post page settings
  show_updated = false # default

  [params.comments]
    enabled = false # default
    engine = "disqus" # more supported engines will be added.

  # the value of name should be an valid font awesome icon name (brands type)
  # https://fontawesome.com/icons?d=gallery&s=brands
  [[params.social]]
    name = "github"
    link = "https://github.com/dionizh"
  [[params.social]]
    name = "linkedin"
    link = "https://www.linkedin.com/in/dionizhong/"
  [[params.social]]
    name = "email"
    link = "dioniys@yahoo.com"  # no need for "mailto:" in the head
    